### ISSUE TITLE
Edge support

### ISSUE THREAD

**Issue by henon** [skclusive/Skclusive.Material.Component#46]
I don't need Edge right now, so no hurry. I just tried the minimal Material examples in `Microsoft Edge 44.18362.449.0` and here is my report:

### Material.Server.Host
* Drawer is not showing
* on the counter Page Button can not be clicked, increment not going up
* Ripple not showing on button click

Error message in JavaScript console:
```
[2020-06-20T09:43:41.801Z] Error: Microsoft.JSInterop.JSException: Could not find 'Skclusive' in 'window'.
Error: Could not find 'Skclusive' in 'window'.
   at Anonymous function (https://localhost:44314/_framework/blazor.server.js:8:30742)
   at Array.prototype.forEach (native code)
   at p (https://localhost:44314/_framework/blazor.server.js:8:30693)
   at Anonymous function (https://localhost:44314/_framework/blazor.server.js:8:31414)
   at Promise (native code)
   at e.jsCallDispatcher.beginInvokeJSFromDotNet (https://localhost:44314/_framework/blazor.server.js:8:31384)
   at Anonymous function (https://localhost:44314/_framework/blazor.server.js:1:19193)
   at Array.prototype.forEach (native code)
   at e.prototype.invokeClientMethod (https://localhost:44314/_framework/blazor.server.js:1:19171)
   at e.prototype.processIncomingData (https://localhost:44314/_framework/blazor.server.js:1:17160)

   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)

   at Mi
```
### Material.Browser.Host
* Drawer not showing
* Counter is working, increment goes up!
* Ripple is not showing on button click

Error messages in console:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'Skclusive' in 'window'.
      Error: Could not find 'Skclusive' in 'window'.
         at Anonymous function (https://localhost:5001/_framework/blazor.webassembly.js:1:9192)
         at Array.prototype.forEach (native code)
         at p (https://localhost:5001/_framework/blazor.webassembly.js:1:9142)
         at Anonymous function (https://localhost:5001/_framework/blazor.webassembly.js:1:9866)
         at Promise (native code)
         at e.jsCallDispatcher.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:9835)
         at _mono_wasm_invoke_js_marshalled (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:171315)
         at Module[_mono_wasm_invoke_method] (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:195702)
         at BINDING.call_method (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:160862)
         at BINDING.set_task_result (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:150613)
Microsoft.JSInterop.JSException: Could not find 'Skclusive' in 'window'.
Error: Could not find 'Skclusive' in 'window'.
   at Anonymous function (https://localhost:5001/_framework/blazor.webassembly.js:1:9192)
   at Array.prototype.forEach (native code)
   at p (https://localhost:5001/_framework/blazor.webassembly.js:1:9142)
   at Anonymous function (https://localhost:5001/_framework/blazor.webassembly.js:1:9866)
   at Promise (native code)
   at e.jsCallDispatcher.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:9835)
   at _mono_wasm_invoke_js_marshalled (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:171315)
   at Module[_mono_wasm_invoke_method] (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:195702)
   at BINDING.call_method (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:160862)
   at BINDING.set_task_result (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:150613)
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x343bbb8 + 0x0002c> in <filename unknown>:0 
  at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync (Microsoft.JSInterop.IJSRuntime jsRuntime, System.String identifier, System.Object[] args) <0x334e0a8 + 0x000e4> in <filename unknown>:0 
  at Skclusive.Script.DomHelpers.DomHelpers.MoveContentAsync (System.Nullable`1[T] source, System.Nullable`1[T] target, System.Nullable`1[T] targetBody) <0x334d540 + 0x00138> in <filename unknown>:0 
  at Skclusive.Material.Core.Portal.OnAfterRenderAsync () <0x334ab90 + 0x00226> in <filename unknown>:0 
  at Skclusive.Core.Component.RenderComponentBase.OnAfterRenderAsync (System.Boolean firstRender) <0x3349138 + 0x002a8> in <filename unknown>:0 
  at Skclusive.Core.Component.DisposableComponentBase.OnAfterRenderAsync (System.Boolean firstRender) <0x3343900 + 0x000d4> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x335e1e0 + 0x000ca> in <filename unknown>:0 
blazor.webassembly.js (1,37753)

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'Skclusive' in 'window'.
      Error: Could not find 'Skclusive' in 'window'.
         at Anonymous function (https://localhost:5001/_framework/blazor.webassembly.js:1:9192)
         at Array.prototype.forEach (native code)
         at p (https://localhost:5001/_framework/blazor.webassembly.js:1:9142)
         at Anonymous function (https://localhost:5001/_framework/blazor.webassembly.js:1:9866)
         at Promise (native code)
         at e.jsCallDispatcher.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:9835)
         at _mono_wasm_invoke_js_marshalled (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:171315)
         at Module[_mono_wasm_invoke_method] (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:195702)
         at BINDING.call_method (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:160862)
         at BINDING.set_task_result (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:150613)
Microsoft.JSInterop.JSException: Could not find 'Skclusive' in 'window'.
Error: Could not find 'Skclusive' in 'window'.
   at Anonymous function (https://localhost:5001/_framework/blazor.webassembly.js:1:9192)
   at Array.prototype.forEach (native code)
   at p (https://localhost:5001/_framework/blazor.webassembly.js:1:9142)
   at Anonymous function (https://localhost:5001/_framework/blazor.webassembly.js:1:9866)
   at Promise (native code)
   at e.jsCallDispatcher.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:9835)
   at _mono_wasm_invoke_js_marshalled (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:171315)
   at Module[_mono_wasm_invoke_method] (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:195702)
   at BINDING.call_method (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:160862)
   at BINDING.set_task_result (https://localhost:5001/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:150613)
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x343bbb8 + 0x0002c> in <filename unknown>:0 
  at Skclusive.Material.Script.EventDelegator.RegisterAsync (Microsoft.AspNetCore.Components.ElementReference reference, System.String name, System.Int32 delay) <0x33643d8 + 0x00116> in <filename unknown>:0 
  at Skclusive.Material.Transition.SlideComponent.OnAfterMountAsync () <0x3363a78 + 0x001d4> in <filename unknown>:0 
  at Skclusive.Core.Component.RenderComponentBase.OnAfterRenderAsync (System.Boolean firstRender) <0x3349138 + 0x00114> in <filename unknown>:0 
  at Skclusive.Core.Component.DisposableComponentBase.OnAfterRenderAsync (System.Boolean firstRender) <0x3343900 + 0x000d4> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x335e1e0 + 0x000ca> in <filename unknown>:0 
blazor.webassembly.js (1,37753)

2SCRIPT1028: SCRIPT1028: Expected identifier, string or number
counter (1,2028)
```

**Comment by skclusive** [comment]
i guess this is similar to #56 which is fixed in preview release in develop branch. closing it now. please do reopen if reproducible.
