### ISSUE TITLE
Unhandled exception rendering component: Cannot read property 'insertBefore' of null

### ISSUE THREAD

**Issue by gkarnik05** [skclusive/Skclusive.Material.Component#77]
When I try to run the solution, I get the below error in the console:
'crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read property 'insertBefore' of null
      TypeError: Cannot read property 'insertBefore' of null
          at s (https://localhost:44381/_framework/blazor.webassembly.js:1:8901)
          at Object.t.createAndInsertLogicalContainer (https://localhost:44381/_framework/blazor.webassembly.js:1:9936)
          at e.insertComponent (https://localhost:44381/_framework/blazor.webassembly.js:1:35986)
          at e.insertFrame (https://localhost:44381/_framework/blazor.webassembly.js:1:34601)
          at e.applyEdits (https://localhost:44381/_framework/blazor.webassembly.js:1:32736)
          at e.updateComponent (https://localhost:44381/_framework/blazor.webassembly.js:1:32052)
          at Object.t.renderBatch (https://localhost:44381/_framework/blazor.webassembly.js:1:11924)
          at Object.window.Blazor._internal.renderBatch (https://localhost:44381/_framework/blazor.webassembly.js:1:61687)
          at Object.w [as invokeJSFromDotNet] (https://localhost:44381/_framework/blazor.webassembly.js:1:64209)
          at _mono_wasm_invoke_js_blazor (https://localhost:44381/_framework/dotnet.5.0.0.js:1:190800)
Microsoft.JSInterop.JSException: Cannot read property 'insertBefore' of null
TypeError: Cannot read property 'insertBefore' of null
    at s (https://localhost:44381/_framework/blazor.webassembly.js:1:8901)
    at Object.t.createAndInsertLogicalContainer (https://localhost:44381/_framework/blazor.webassembly.js:1:9936)
    at e.insertComponent (https://localhost:44381/_framework/blazor.webassembly.js:1:35986)
    at e.insertFrame (https://localhost:44381/_framework/blazor.webassembly.js:1:34601)
    at e.applyEdits (https://localhost:44381/_framework/blazor.webassembly.js:1:32736)
    at e.updateComponent (https://localhost:44381/_framework/blazor.webassembly.js:1:32052)
    at Object.t.renderBatch (https://localhost:44381/_framework/blazor.webassembly.js:1:11924)
    at Object.window.Blazor._internal.renderBatch (https://localhost:44381/_framework/blazor.webassembly.js:1:61687)
    at Object.w [as invokeJSFromDotNet] (https://localhost:44381/_framework/blazor.webassembly.js:1:64209)
    at _mono_wasm_invoke_js_blazor (https://localhost:44381/_framework/dotnet.5.0.0.js:1:190800)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
d.printErr @ blazor.webassembly.js:1
d.preRun.push.window.Blazor._internal.dotNetCriticalError @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.0.js:1
do_icall @ 00aba1c6:0x194e46
do_icall_wrapper @ 00aba1c6:0x79df6
interp_exec_method @ 00aba1c6:0x44ad0
interp_runtime_invoke @ 00aba1c6:0x12efed
mono_jit_runtime_invoke @ 00aba1c6:0x118e4d
do_runtime_invoke @ 00aba1c6:0x79d3f
mono_runtime_try_invoke @ 00aba1c6:0x1297f
mono_runtime_invoke @ 00aba1c6:0x10ec19
mono_wasm_invoke_method @ 00aba1c6:0x108e40
Module._mono_wasm_invoke_method @ dotnet.5.0.0.js:1
call_method @ dotnet.5.0.0.js:1
set_task_result @ dotnet.5.0.0.js:1
(anonymous) @ dotnet.5.0.0.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.0.js:1
d.preRun.push.window.Blazor._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.0.js:1
do_icall @ 00aba1c6:0x194e46
do_icall_wrapper @ 00aba1c6:0x79df6
interp_exec_method @ 00aba1c6:0x44ad0
interp_runtime_invoke @ 00aba1c6:0x12efed
mono_jit_runtime_invoke @ 00aba1c6:0x118e4d
do_runtime_invoke @ 00aba1c6:0x79d3f
mono_runtime_invoke_checked @ 00aba1c6:0xf65a
mono_runtime_try_invoke_array @ 00aba1c6:0x10e81f
ves_icall_InternalInvoke @ 00aba1c6:0xed48f
ves_icall_InternalInvoke_raw @ 00aba1c6:0xecf54
do_icall @ 00aba1c6:0x194dd3
do_icall_wrapper @ 00aba1c6:0x79df6
interp_exec_method @ 00aba1c6:0x44ad0
interp_runtime_invoke @ 00aba1c6:0x12efed
mono_jit_runtime_invoke @ 00aba1c6:0x118e4d
do_runtime_invoke @ 00aba1c6:0x79d3f
mono_runtime_try_invoke @ 00aba1c6:0x1297f
mono_runtime_invoke @ 00aba1c6:0x10ec19
mono_wasm_invoke_method @ 00aba1c6:0x108e40
Module._mono_wasm_invoke_method @ dotnet.5.0.0.js:1
call_method @ dotnet.5.0.0.js:1
(anonymous) @ dotnet.5.0.0.js:1
callEntryPoint @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
a @ blazor.webassembly.js:1
Promise.then (async)
u @ blazor.webassembly.js:1
a @ blazor.webassembly.js:1
Promise.then (async)
u @ blazor.webassembly.js:1
a @ blazor.webassembly.js:1
Promise.then (async)
u @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
g @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
n @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: No element is currently associated with component 800
      Error: No element is currently associated with component 800
          at e.updateComponent (https://localhost:44381/_framework/blazor.webassembly.js:1:31484)
          at Object.t.renderBatch (https://localhost:44381/_framework/blazor.webassembly.js:1:11924)
          at Object.window.Blazor._internal.renderBatch (https://localhost:44381/_framework/blazor.webassembly.js:1:61687)
          at Object.w [as invokeJSFromDotNet] (https://localhost:44381/_framework/blazor.webassembly.js:1:64209)
          at _mono_wasm_invoke_js_blazor (https://localhost:44381/_framework/dotnet.5.0.0.js:1:190800)
          at wasm_invoke_iiiiii (<anonymous>:wasm-function[5611]:0xdda7c)
          at ves_pinvoke_method (<anonymous>:wasm-function[5708]:0xdfb5f)
          at interp_exec_method (<anonymous>:wasm-function[2155]:0x44c05)
          at interp_runtime_invoke (<anonymous>:wasm-function[7861]:0x12efed)
          at mono_jit_runtime_invoke (<anonymous>:wasm-function[7346]:0x118e4d)
Microsoft.JSInterop.JSException: No element is currently associated with component 800
Error: No element is currently associated with component 800
    at e.updateComponent (https://localhost:44381/_framework/blazor.webassembly.js:1:31484)
    at Object.t.renderBatch (https://localhost:44381/_framework/blazor.webassembly.js:1:11924)
    at Object.window.Blazor._internal.renderBatch (https://localhost:44381/_framework/blazor.webassembly.js:1:61687)
    at Object.w [as invokeJSFromDotNet] (https://localhost:44381/_framework/blazor.webassembly.js:1:64209)
    at _mono_wasm_invoke_js_blazor (https://localhost:44381/_framework/dotnet.5.0.0.js:1:190800)
    at wasm_invoke_iiiiii (<anonymous>:wasm-function[5611]:0xdda7c)
    at ves_pinvoke_method (<anonymous>:wasm-function[5708]:0xdfb5f)
    at interp_exec_method (<anonymous>:wasm-function[2155]:0x44c05)
    at interp_runtime_invoke (<anonymous>:wasm-function[7861]:0x12efed)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7346]:0x118e4d)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()'

**Comment by skclusive** [comment]
could you share which repo and project that you are trying to run? Skclusive.Samples?

**Comment by gkarnik05** [comment]
Yes, Skclusive.Blazor.Samples repo. I see that the Dashboard.Browser.Host project is set as the startup project.
![image](https://user-images.githubusercontent.com/37911922/101270511-be7b2000-379f-11eb-8936-9349a0d5b626.png)

**Comment by skclusive** [comment]
could you try the same in dotnet cli? i do not have windows machine to reproduce the issue.
